brace_style = "PreferSameLine"
fn_single_line = true
format_strings = true
group_imports = "StdExternalCrate"
hex_literal_case = "Lower"
newline_style = "Unix"
normalize_comments = true
overflow_delimited_expr = true
reorder_impl_items = true
wrap_comments = true